### ISSUE TITLE
Bucket name restrictions

### ISSUE THREAD

**Issue by hawesie** [awsdocs/aws-robomaker-developer-guide#3]
The developer guide suggests bucket names as follows:

```
aws s3 mb s3://MyApplicationSource
```

However capital letters are not allowed in bucket names, so it's not possible to copy the commands directly from the tutorial to execute.

**Comment by ebattalio** [comment]
Thanks Nick, this will be fixed in the online this week. GitHub source will be updated in the near future.

**Comment by davidmgre** [comment]
PR: https://github.com/awsdocs/aws-robomaker-developer-guide/pull/4

**Comment by ebattalio** [comment]
Updated, thanks.
